// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJQ47F80hSoeJ2irS7ljIi0aawb0RrHJk',
    appId: '1:76929705254:web:a65b0b2be419f76e750de7',
    messagingSenderId: '76929705254',
    projectId: 'scrivia-47b4a',
    authDomain: 'scrivia-47b4a.firebaseapp.com',
    storageBucket: 'scrivia-47b4a.firebasestorage.app',
    measurementId: 'G-TQ27WDKL4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC63mWrLuqs-awy0gIpGmOmPqKiJVO2jJQ',
    appId: '1:76929705254:android:728cfa4a9201b863750de7',
    messagingSenderId: '76929705254',
    projectId: 'scrivia-47b4a',
    storageBucket: 'scrivia-47b4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXTwxghR7jgo6B70xm9IfXILJinr5RZrk',
    appId: '1:76929705254:ios:0f5947899b47fbc7750de7',
    messagingSenderId: '76929705254',
    projectId: 'scrivia-47b4a',
    storageBucket: 'scrivia-47b4a.firebasestorage.app',
    iosBundleId: 'com.scrivia.scrivia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXTwxghR7jgo6B70xm9IfXILJinr5RZrk',
    appId: '1:76929705254:ios:0f5947899b47fbc7750de7',
    messagingSenderId: '76929705254',
    projectId: 'scrivia-47b4a',
    storageBucket: 'scrivia-47b4a.firebasestorage.app',
    iosBundleId: 'com.scrivia.scrivia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJQ47F80hSoeJ2irS7ljIi0aawb0RrHJk',
    appId: '1:76929705254:web:de605df4583fd5ad750de7',
    messagingSenderId: '76929705254',
    projectId: 'scrivia-47b4a',
    authDomain: 'scrivia-47b4a.firebaseapp.com',
    storageBucket: 'scrivia-47b4a.firebasestorage.app',
    measurementId: 'G-MHP3DFVQ15',
  );
}
